### Mini test

In [3]:
import torch

In [5]:
A = torch.arange(3).reshape(3, 1)
B = torch.arange(4).reshape(1, 4)

In [7]:
A

tensor([[0],
        [1],
        [2]])

In [8]:
B

tensor([[0, 1, 2, 3]])

In [9]:
A + B

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

### 2. Hadamard product vs matrix duplication

In [13]:
# Hadamard
A = torch.arange(4).reshape(2, 2)
print(A)
B = torch.arange(4, 8).reshape(2, 2)
print(B)

tensor([[0, 1],
        [2, 3]])
tensor([[4, 5],
        [6, 7]])


In [14]:
A * B

tensor([[ 0,  5],
        [12, 21]])

In [15]:
# Matrix multiplication
torch.mm(A, B)

tensor([[ 6,  7],
        [26, 31]])