# Linear Algebra

## TL;DR
Linear algebra là "ngôn ngữ toán học" mà Deep Learning dùng để nói chuyện. Một ảnh = ma trận số. Weights của mạng nơ-ron = ma trận. Forward pass = nhân ma trận. Gradient = vector đạo hàm. Nếu Tensor Operations là "vật chứa dữ liệu", thì Linear Algebra là các phép tính trên vật chứa đó — đặc biệt là các phép nhân ma trận làm biến đổi dữ liệu qua từng lớp của mạng.

## Phân cấp đối tượng

| Object     | Ký hiệu                                  | Code (PyTorch)                    | Rank | Ví dụ DL                  |
| ---------- | ---------------------------------------- | --------------------------------- | ---- | ------------------------- |
| **Scalar** | $x \in \mathbb{R}$                       | `torch.tensor(3.0)`               | 0D   | Learning rate, loss value |
| **Vector** | $\mathbf{x} \in \mathbb{R}^n$            | `torch.arange(3)`                 | 1D   | Bias, embedding vector    |
| **Matrix** | $\mathbf{A} \in \mathbb{R}^{m \times n}$ | `A.reshape(m, n)`                 | 2D   | Weight matrix của 1 layer |
| **Tensor** | $\mathsf{X}$                             | `torch.arange(24).reshape(2,3,4)` | nD   | Batch ảnh, activations    |

## Phép toán Reduction
ELI5
"Reduction" nghĩa là nén lại. Bạn có ma trận 3×4 = 12 số. Cộng tất cả → 1 số (reduce hết). Cộng theo hàng → vector 4 số (reduce axis 0). Cộng theo cột → vector 3 số (reduce axis 1).

### Sum & Mean

In [9]:
import torch
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
print(A.sum())  # Tổng tất cả phần tử
print(A.sum(axis=0))  # Tổng theo cột (giữ nguyên số cột)
print(A.sum(axis=1))  # Tổng theo hàng (giữ nguyên số hàng

tensor(66.)
tensor([12., 15., 18., 21.])
tensor([ 6., 22., 38.])


In [11]:
print(A.mean())

print(A.mean(axis=0))  # Trung bình theo cột
print(A.mean(axis=1))  # Trung bình theo hàng

tensor(5.5000)
tensor([4., 5., 6., 7.])
tensor([1.5000, 5.5000, 9.5000])


### Keep dims

In [13]:
A.sum(axis=1) # no keepdims


tensor([ 6., 22., 38.])

In [14]:
A.sum(axis=1, keepdims=True)  # Giữ nguyên chiều sau khi giảm

tensor([[ 6.],
        [22.],
        [38.]])

Sử dụng `keepdims=True` để giữ nguyên số chiều sau khi giảm. Ví dụ, nếu bạn có ma trận 3×4 và cộng theo hàng (axis=1), kết quả sẽ là vector 3 số. Nhưng nếu bạn dùng `keepdims=True`, kết quả sẽ là ma trận 3×1, giữ nguyên số hàng nhưng chỉ còn 1 cột. Điều này hữu ích khi bạn muốn thực hiện các phép toán tiếp theo mà yêu cầu kích thước cụ thể.

In [16]:
A.cumsum(axis=0)  # Cộng dồn theo cột

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

Dot product


In [21]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.ones(3)

print(torch.dot(x, y))  # Tích vô hướng (dot product) giữa x và y
print(torch.sum(x * y))  # Cách khác để tính tích vô hướng bằng cách nhân phần tử và cộng lại

print(torch.sum(x * y)==torch.dot(x, y))  # Cách khác để tính tích vô hướng bằng cách nhân phần tử và cộng lại

tensor(6.)
tensor(6.)
tensor(True)


## Norms - Độ dài của vector

Định nghĩa
- Một norm phải thỏa mãn 3 tính chất:
    1. **Non-negativity**: $\|\mathbf{x}\| \geq 0$ và $\|\mathbf{x}\| = 0$ nếu và chỉ nếu $\mathbf{x} = \mathbf{0}$.
    2. **Homogeneity**: $\|\alpha \mathbf{x}\| = |\alpha| \|\mathbf{x}\|$ với mọi scalar $\alpha$.
    3. **Triangle inequality**: $\|\mathbf{x} + \mathbf{y}\| \leq \|\mathbf{x}\| + \|\mathbf{y}\|$.

L2 norm - Euclidean norm

In [22]:
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))  # L2 norm (Euclidean norm) của u

tensor(5.)


L1 norm - Manhattan norm

In [27]:
u = torch.tensor([3.0, -4.0])
print(torch.abs(u).sum())  # L1 norm (Manhattan norm) của u

tensor(7.)


$L^p$ norm - Generalized norm

$$|x|_p = \left(\sum_{i=1}^n |x_i|^p\right)^{1/p}$$

---
Frobenius norm 
- Ma trận có nhiều chiều hơn vector, nên chúng ta cần một cách để đo "độ dài" của ma trận. Frobenius norm là một cách để làm điều đó, bằng cách tính căn bậc hai của tổng bình phương tất cả phần tử trong ma trận.

$$||X||_F=\sqrt{\sum_{i=1}^m \sum_{j=1}^n |x_{ij}|^2}$$

In [29]:
X = torch.tensor([[0.0, 1.0], [2.0, 3.0]])

print(f"torch.norm(X): {torch.norm(X)} = (0^2 + 1^2 + 2^2 + 3^2)^{{1/2}}")  # Frobenius norm của X

torch.norm(X): 3.7416574954986572 = (0^2 + 1^2 + 2^2 + 3^2)^{1/2}


## Exercises

Note: 
- Hadamard - Nhân phần tử (element-wise multiplication)
- Matmul - Nhân ma trận (matrix multiplication)
- Dot product - Tích vô hướng (scalar product) của hai vector, bằng tổng tích của các phần tử tương ứng.

In [31]:
A = torch.arange(9).reshape(3, 3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
X = A @ A.T
X

tensor([[  5,  14,  23],
        [ 14,  50,  86],
        [ 23,  86, 149]])

L1 norm 

$$u = [3, -4, 0] -> |3| + |-4| + |0| = 7
$$
L2 norm 

$$u = [3, -4, 0] -> sqrt(3^2 + (-4)^2 + 0^2) = 5$$