In [2]:
import torch

x = torch.arange(12,dtype=torch.float32)


In [3]:
x.numel() # length

12

In [4]:
x.shape

torch.Size([12])

# Reshape

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
X = x.reshape(4,3)
X

X = x.reshape(2,6)
X

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

torch.zeros((2,3,4)) # 3D array of zeros

## Indexing and slicing


In [15]:
X=torch.arange(20).reshape(4,5)

In [18]:
print(X[-1])

print(X[1:3])

print(X[1:3,0:2])

print(X[0:2,:])

tensor([15, 16, 17, 18, 19])
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 5,  6],
        [10, 11]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


## Element-wise operations

In [19]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(f"{x} + {y} = {x + y}")

print(f"{x} - {y} = {x - y}")

print(f"{x} * {y} = {x * y}")

print(f"{x} / {y} = {x / y}")

print(f"{x} ** {y} = {x ** y}")

tensor([1, 2, 4, 8]) + tensor([2, 2, 2, 2]) = tensor([ 3,  4,  6, 10])
tensor([1, 2, 4, 8]) - tensor([2, 2, 2, 2]) = tensor([-1,  0,  2,  6])
tensor([1, 2, 4, 8]) * tensor([2, 2, 2, 2]) = tensor([ 2,  4,  8, 16])
tensor([1, 2, 4, 8]) / tensor([2, 2, 2, 2]) = tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([1, 2, 4, 8]) ** tensor([2, 2, 2, 2]) = tensor([ 1,  4, 16, 64])


## Concatenation

In [20]:
torch.cat((x, y), dim=0)  # concatenate by rows (dim=0)

tensor([1, 2, 4, 8, 2, 2, 2, 2])

In [25]:
print(X)
Y = torch.arange(20, 24).reshape(4, 1)
torch.cat((X,Y),dim=1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


tensor([[ 0,  1,  2,  3,  4, 20],
        [ 5,  6,  7,  8,  9, 21],
        [10, 11, 12, 13, 14, 22],
        [15, 16, 17, 18, 19, 23]])

In [27]:
X.sum()

tensor(190)

## Broadcasting

In [28]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a+b

# a:        b:
# [[0],     [[0, 1]]
#  [1],
#  [2]]

# Sau broadcasting:
# a → [[0, 0],    b → [[0, 1],
#      [1, 1],         [0, 1],
#      [2, 2]]         [0, 1]]

a + b
# tensor([[0, 1],
#          [1, 2],
#          [2, 3]])

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Conversions

In [31]:
A = X.numpy()
B = torch.from_numpy(A)

In [33]:
a = torch.tensor([0.0])
a.item() # only one element tensor
float(a) # only one element tensor
int(a) # only one element tensor

0

---
## Exercises

In [36]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(X)
Y = torch.tensor([[0.0], [1.0], [2.0]])
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[0.],
        [1.],
        [2.]])


In [37]:
print(X == Y)
print(X > Y)
print(X < Y)

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
A = torch.tensor()